Path_exists() function
casey/just pull request #1106
Opened 2022-02-17 12:56 UTC by heavelock

Hey! 
So here is promised PR for `path_exists()`. 
I also added tests for dirs and files, should I also add tests for hard/soft links? And sorry for their general clumsiness, I'm writing rust basically for the first time and I still have to wrap my head around it.

Closes: #1102

2022-02-19 22:38 UTC, casey requested changes
> Hey! So here is promised PR for `path_exists()`. I also added tests for dirs and files, should I also add tests for hard/soft links?

Since we're using `Path::exists`, which is provided to us, we don't need fully comprehensive tests. In general, I think it's safe to assume that you're dependencies are correct, especially when it comes from the standard library. So for this, I think we can just have one test when a file exists, and another when it doesn't.

> And sorry for their general clumsiness, I'm writing rust basically for the first time and I still have to wrap my head around it.

No worries, rust is hard, and the way just runs tests is ideosyncratic!

2022-02-19 22:38 UTC, casey commented on tests/functions.rs
> +  test
You can use `Test::tree` to populate the tempdir the test runs in with files:

```suggestion
  Test::new()
    .tree(tree! {
      testfile: ""
    })
```

2022-02-19 22:38 UTC, casey commented on tests/functions.rs
> +    ))
You should just be able to do:

```suggestion
    .justfile("x := path_exists('testfile')")
```

2022-02-19 22:38 UTC, casey commented on tests/functions.rs
> +    .unindent_stdout(false)
```suggestion
    .stdout("true\n")
```

2022-02-19 22:38 UTC, casey commented on tests/functions.rs
> +    .run();
These comments also apply for the rest of the tests.

2022-02-21 11:09 UTC, heavelock commented
Thanks for your comments! I applied your suggestions and removed the tests for directories since we don't necessarily need to test for them.

Should I somehow refer in docs that this function is using internally rust's std behaviour?

2022-02-21 11:40 UTC, casey commented
I think it probably isn't necessary to reference the stdlib function. I looked at the documentation for Path::exists, and we could probably include some of the details. I also think it's probably a good idea to put the function under a more descriptive heading, maybe, so something like:


```
#### Filesystem Access

- `path_exists(path)` - Returns `true` if the path points at an existing entity and `false` otherwise. Traverses symbolic links, and returns `false` if the path is inaccessible or points to a broken symlink.
```

2022-02-21 16:03 UTC, heavelock commented
I changed the readme entry according to your suggestion.

2022-02-21 21:45 UTC, merged

2022-02-21 21:46 UTC, casey commented
Nice, merged! Thank you for the PR! I think there are probably a lot of other useful boolean functions that can be added now.