UUID and sha256 digest functions
casey/just pull request #1170
Opened 2022-05-01 21:10 UTC by mbodmer

issue #1018 mentioned a uuid function would be helpful.

Here is my attempt to deliver this. Also I've included sha256 hashing functions for strings and files.

To create a meaningful unittest for uuid() I had to refactor the Test struct in test.rs, I hope this is acceptable. The challenge was to keep the current interface but allow for custom verification. Well, here is my attempt. I'm new to rust, so bear with me.

2022-05-02 17:10 UTC, mbodmer commented
#1011

2022-05-03 02:14 UTC, casey commented
Thanks for this PR! There's already `Test::stderr_regex`, and I think it might be cleaner to add a `Test::stdout_regex` to test that the output matches a pattern, instead of adding a new kind of validator. for UUIDs, it should be okay to check that it matches the pattern `/........-....-....-....-............/`

For the hash functions, can you use the implementation from https://github.com/RustCrypto/hashes? I think it's better maintained.

2022-05-03 06:20 UTC, mbodmer commented
Hi, thanks for your review. I have now added stdout_regex in the sense of the existing stderr_regex. I agree, much less complexity that way. Also I have replaced the hashing dependency with rust-crypto. Hope this helps.

2022-05-03 06:23 UTC, mbodmer commented
I'm not sure whether the general name digest()/digest_file() for the functions is too broad. Any requests for a better more concise name? :-)
eg: sha256()/sha256_file()

2022-05-03 06:35 UTC, casey commented
> I'm not sure whether the general name digest()/digest_file() for the functions is too broad. Any requests for a better more concise name? :-) eg: sha256()/sha256_file()

I think I agree, `sha256()` and `sha256_file()` are probably better, so if you're reading a justfile and you don't know the function you can see what it does without having to look up documentation.

2022-05-03 10:02 UTC, mbodmer commented
Ok, they are now renamed to the more specific `sha256()`, `sha256_file()`

2022-05-04 05:28 UTC, casey requested changes
Nice, looking good. I added a few minor comments.

2022-05-04 05:28 UTC, casey commented on README.md
> +- `sha256(textdata)` Generates a sha256 hash of the given text data. Example: `sha256("just hello")`
```suggestion
- `sha256(string)` Return the SHA-256 hash of `string` as a hexadecimal string.
```

2022-05-04 05:28 UTC, casey commented on README.md
> +- `sha256_file(path)` Generates a sha256 hash of the given file. Example: `sha256_file("/path/to/file")`
```suggestion
- `sha256_file(path)` Return the SHA-256 hash of the file at `path` as a hexadecimal string.
```

2022-05-04 05:28 UTC, casey commented on README.md
> +- `uuid()` - Randomly generates a hyphenated UUID string.
```suggestion
- `uuid()` - Return a randomly generated UUID.
```

2022-05-04 05:28 UTC, casey commented on src/function.rs
> +  std::io::copy(&mut file, &mut hasher).unwrap();
These unwraps should both be handled. Something like:

```suggestion
  let mut file = std::fs::File::open(path).map_err(|err| format!("Failed to open file at `{}`: {}", path, err))?;
  std::io::copy(&mut file, &mut hasher).map_err(|err| format!("Failed to read file at `{}`: {}", path, err)?;
```

2022-05-04 05:28 UTC, casey commented on tests/functions.rs
> +  writeln!(tmpfile, "just is great").unwrap();
❤️

2022-05-04 05:28 UTC, casey commented on tests/functions.rs
> +    .justfile(justfile_content)
You can use the somewhat odd `tree` function to populate the tempdir with files:

```suggestion
    .justfile("x := sha256_file('file')")
    .tree(tree! {
      file: "just is great",
    })
```

2022-05-04 18:05 UTC, mbodmer commented
Thanks for the extensive review, I think I've covered all your issues now, feel free to check again

2022-05-04 20:11 UTC, casey requested changes
Nice, looks good, although I just realized that there's a bug. `just` doesn't change the working directory, so you'll need to join the `path` in `sha256_file` with `context.search.working_directory`, i.e. `context.search.working_directory.join(path)`.

Could you also add a test for this? It should fail on the current PR, and then pass once `path` is joined with the working directory. You can use `Test::current_dir` to make just start in a sub-directory of the tmpdir. You can try to do `sha256_file` on a file in tempdir.

2022-05-04 20:25 UTC, mbodmer commented
Sorry for force pushing, I've had to rewrite the history to rebase the branch, since you've also modified the lockfile and stupid me checked it in, in a commit together with other changes.
Can you give me more details, I don't understand where, how and what causes the bug you've mentioned.

2022-05-04 20:38 UTC, casey commented
Lets say you have the following files:

```
/justfile
/bar
/foo/
```

And you're currently in `/foo/`. `/justfile` contains:

```
baz:
  echo {{sha256_file("bar")}}}
```

You do:

```
$ just
```

The `just` executable looks for the justfile and sees that it's in `/`, so it sets `search.working_directory` to `/`. However, it does not call `env::set_current_dir` with `/`, so the current directory is still `/bar`. So then `sha256_file("bar")` will fail, because there is no `/foo/bar`.

2022-05-04 20:48 UTC, mbodmer commented
Ok, I think now I understand, thanks. Will try

2022-05-04 23:14 UTC, casey commented on src/function.rs
> +  let justpath = _context.search.working_directory.join(path);
The `_` can be removed now that we're using context. The `_` is just to make rust not complain about an unused variable.

```suggestion
fn sha256_file(context: &FunctionContext, path: &str) -> Result<String, String> {
  use sha2::{Digest, Sha256};
  let justpath = context.search.working_directory.join(path);
```

2022-05-04 23:15 UTC, casey approved these changes
Looks good! I went ahead and removed a `_` that is now unnecessary.

2022-05-04 23:18 UTC, merged

2022-05-05 05:19 UTC, mbodmer commented
Thanks