Support escaping newlines
casey/just pull request #1551
Opened 2023-02-17 20:40 UTC by ids1024

Fixes https://github.com/casey/just/issues/1157.

2023-06-13 11:46 UTC, casey requested changes
Looks good to me! Can you add tests that cover:

1. Escaping a `\r\n`
2. The unpaired `\r\n` error
3. The invalid escape sequence error?

2023-06-13 11:46 UTC, casey commented on src/lexer.rs
> +      return Err(self.error(CompileErrorKind::InvalidEscapeSequence { character: next }));
```suggestion
    } else if let Some(character) = self.next {
      return Err(self.error(CompileErrorKind::InvalidEscapeSequence { character }));
```

2023-07-24 23:13 UTC, ids1024 commented
Updated.

2023-07-25 09:05 UTC, merged

2023-07-25 09:12 UTC, casey commented
Nice, merged!

2023-07-30 21:05 UTC, nk9 commented
@casey, @laniakea64 has noticed that this works in a bunch of other cases. See https://github.com/nk9/just_sublime/issues/23 and this gist: https://gist.github.com/laniakea64/b3381389beca11226cb8fefc4e1abf85

Just wanted to check: is this intentional/desired? If it is, there should probably be a lot more tests.