Allow --unstable to be set with an environment variable
casey/just pull request #1588
Opened 2023-04-21 06:38 UTC by neunenak

Allow the environment variable JUST_ALLOW_UNSTABLE=true to act as equivalent to the --unstable flag. Any other value of JUST_ALLOW_UNSTABLE is treated as false. 

This addresses https://github.com/casey/just/issues/1575

2023-06-13 11:39 UTC, casey requested changes
Just a few random nitpicks, see comments. Also: Is there any sort of convention regarding how other tools convert environment variable values are converted to bools? For example, Rust has the `RUST_BACKTRACE` variable, which if unset or set to `0` will not capture a backtrace, but if set to any other value will. I wonder if there's any particular reason to go with one standard vs another.

2023-06-13 11:39 UTC, casey commented on src/config.rs
> +pub(crate) const UNSTABLE_KEY: &str = "JUST_ALLOW_UNSTABLE";
What about `JUST_UNSTABLE` instead? `JUST_UNSTABLE=true` makes sense, and is shorter.

2023-06-13 11:39 UTC, casey commented on src/config.rs
> +      || std::env::var_os(UNSTABLE_KEY).map_or(false, |val| val.to_string_lossy() == "true");
I'd be inclined to inline this:
```suggestion
      || std::env::var_os("JUST_UNSTABLE").map_or(false, |val| val.to_string_lossy() == "true");
```

2023-06-15 07:21 UTC, neunenak commented
> Just a few random nitpicks, see comments. Also: Is there any sort of convention regarding how other tools convert environment variable values are converted to bools? For example, Rust has the `RUST_BACKTRACE` variable, which if unset or set to `0` will not capture a backtrace, but if set to any other value will. I wonder if there's any particular reason to go with one standard vs another.

I'm not aware of any convention other than what seems reasonable from the perspective of a developer working with standard programming languages. I'd probably allow both "0" and "false" to be treated as a false boolean, the convention that setting the env var to anything else makes it true, seems reasonable to me.

2023-10-09 03:47 UTC, merged

2023-10-09 03:48 UTC, casey commented
Tweaked a little bit and merged. Sorry for letting this sit for so long. In the mean time, `--dump-format json` was stabilized, so I changed the test to use `--fmt` isntead.