Feat/issue 1698 global quiet
casey/just pull request #1704
Opened 2023-10-17 15:17 UTC by dharrigan

Hi,

Here's a first pass at introducing `quiet recipes`. I'm happy to take unboard any thoughts you may have. Not quite sure about the name `set quiet-recipes`, but was struggling to come up with something better (maybe `set globally-quiet`?) :-)

Tests pass (with my additional ones added).

Thank you for your consideration.

-=david=-

2023-10-22 03:38 UTC, casey commented
Thanks for the PR!

Some thoughts:

- Let's call the setting `quiet`, so you can do `set quiet`.
- Let's call the attribute `[noquiet]`
- We could also not have an attribute, and invert the meaning of `@` if `set quiet` is used. So if you `set quiet`, you can do `@recipe:`, which would make that recipe not quiet`. `@` is a bit confusing though, so I'm not convinced either way on this.

2023-10-22 08:18 UTC, dharrigan commented
Hi,

Thank you for your helpful feedback. I'll make the changes within the next few days :-)

With regards the inversion of the `@`. I thought about this and I decided on the principle of least surprise (for the user). They are used to `@` to signify that the recipe (or line) should be quiet, so I didn't want to break that by introducing an inverted case. I would rather accrete changes than break expectations. I then thought that by introducing the attribute of `[no-quiet-recipe]` (now `[no-quiet]`), they could then choose to make it explicit if they want an already demarked recipe of `@` to become non-quiet when the global attribute is used.

So, no surprises was my thoughts behind that one :-)

-=david=-

2023-10-24 06:06 UTC, dharrigan commented
A question...

You've recommended the attribute to be renamed to `noquiet`. However, there is the precedent of `no-exit-message`, with a hyphen between the `no` and the action. Would it be better to be consisent and call the attribute `no-quiet`?

Thank you.

2023-10-24 06:08 UTC, casey commented
Ah, yeah, good catch. In that case it should be `no-quiet`.

2023-12-24 11:18 UTC, dharrigan commented
Hi!

I was wondering if you have had a chance to consider to merge in this PR? Anything else I can do?

Thank you.

-=david=-

2024-01-02 01:17 UTC, casey requested changes
Sorry I was slow getting to this! Check out my review comments.

2024-01-02 01:17 UTC, casey commented on README.md
> +      <td><a href="https://github.com/gentoo-mirror/dm9pZCAq/tree/master/sys-devel/just">dm9pZCAq/sys-devel/just</a></td>
It looks like there are some unrelated changes, and merge conflicts in README.md.

2024-01-02 01:17 UTC, casey commented on README.md
> +| `[no-quiet]`<sup>?</sup>            | Override globally quiet recipes and always echo out the recipe |
We should also add `[quiet]`.

2024-01-02 01:17 UTC, casey commented on README.md
> +setting `set quiet` in the Justfile. For example:
```suggestion
All recipes in a Justfile can be made quiet with `set quiet`:
```

2024-01-02 01:17 UTC, casey commented on README.md
> +ignored: For example:
```suggestion
If a recipe has`[no-quiet]`, then the setting is ignored:
```

2024-01-02 01:17 UTC, casey commented on README.md
> +
```suggestion
```

2024-01-02 01:17 UTC, casey commented on src/attribute.rs
> +  NoQuiet,
These enum variants should be sorted.

2024-01-02 01:17 UTC, casey commented on src/attribute.rs
> +  fn no_exit_message_to_str() {
```suggestion
  fn to_str() {
```

2024-01-02 01:17 UTC, casey commented on src/attribute.rs
> +  #[test]
We can remove this test. The other test is there just to make sure that we're serializing attribute names in kebab-case, but we don't need to test every variant.

2024-01-02 01:17 UTC, casey commented on src/recipe.rs
> +    !self.attributes.contains(&Attribute::NoQuiet)
Should this be inverted, i.e.:

```suggestion
    self.attributes.contains(&Attribute::NoQuiet)
```

2024-01-02 01:17 UTC, casey commented on src/recipe.rs
> +      let quiet_command = self.no_quiet() && context.settings.quiet
This is used to determine if we should strip a leading `@` from the line, so we should only do so if it starts with an `@`:

```suggestion
      let quiet_line = lines.peek().map_or(false, |line| line.is_quiet());
```

2024-01-02 01:17 UTC, casey commented on src/recipe.rs
> +          || config.verbosity.quiet())
I think this should be something like:

```suggestion
        || !((quiet_line ^ self.quiet) || (context.settings.quiet && !self.no_quiet()) || config.verbosity.quiet())
```

2024-01-03 14:55 UTC, dharrigan commented on README.md
> +      <td><a href="https://github.com/gentoo-mirror/dm9pZCAq/tree/master/sys-devel/just">dm9pZCAq/sys-devel/just</a></td>
Fixed

2024-01-03 14:55 UTC, dharrigan commented on README.md
> +| `[no-quiet]`<sup>?</sup>            | Override globally quiet recipes and always echo out the recipe |
There isn't a `[quiet]` attribute, just `[no-quiet]` which overrides the `set quiet` if that's been set.

2024-01-03 14:55 UTC, dharrigan commented on README.md
> +setting `set quiet` in the Justfile. For example:
done

2024-01-03 14:55 UTC, dharrigan commented on README.md
> +ignored: For example:
done

2024-01-03 14:55 UTC, dharrigan commented on README.md
> +
done

2024-01-03 14:55 UTC, dharrigan commented on src/attribute.rs
> +  fn no_exit_message_to_str() {
done

2024-01-03 14:56 UTC, dharrigan commented on src/attribute.rs
> +  #[test]
done

2024-01-03 14:56 UTC, dharrigan commented on src/recipe.rs
> +    !self.attributes.contains(&Attribute::NoQuiet)
done

2024-01-03 14:56 UTC, dharrigan commented on src/recipe.rs
> +      let quiet_command = self.no_quiet() && context.settings.quiet
done

2024-01-03 14:56 UTC, dharrigan commented on src/recipe.rs
> +          || config.verbosity.quiet())
done

2024-01-03 14:56 UTC, dharrigan commented
Hi!

All changes asked for applied. When you can spare the time, have a looksee and see what you think :-)

Thank you.

-=david=-

2024-01-12 03:33 UTC, casey requested changes
Sorry for letting this sit! This looks good, it just needs integration tests, which can go in `tests/quiet.rs`. The tests in that file are using the `test!` macro, which I try to avoid these days, so for examples of how to write tests, check out `tests/modules.rs`. In particular, all the interactions with the quiet setting, the noquiet attribute, quiet lines, and the `@` prefix to both recipes in lines, should be tested.

2024-01-12 17:18 UTC, dharrigan commented
Hi,

Additional integration tests done. I hope this is looking better.

-=david=-

2024-01-12 20:35 UTC, casey approved these changes
Looks good to me!

2024-01-12 20:38 UTC, merged

2024-01-12 20:40 UTC, casey commented
Thanks for the PR! I tweaked it a little bit, simplifying the tests and removing an `if` statement that would never be executed.

This is easily the worst conditional I've ever seen, amazingly using `||`, `!`, `^`, and `&&`:

```rust
      if config.dry_run
        || config.verbosity.loquacious()
        || !((quiet_line ^ self.quiet)
          || (context.settings.quiet && !self.no_quiet())
          || config.verbosity.quiet())
      {
```

But so be it! Functionality for making things quiet or not quiet has just evolved organically over time, so I guess that's just how it is 😂