Add a confirm attribute for recipes
casey/just pull request #1723
Opened 2023-11-12 17:16 UTC by Hwatwasthat

This would add a "Confirm" attribute that requests confirmation before running a recipe. Runs prior to evaluation, and defaults to not running. Potential solution to issue [#1711](https://github.com/casey/just/issues/1711).

2023-11-12 20:57 UTC, casey requested changes
I just added some comments, and I thought of something else: If a recipe doesn't run, any recipe in the current invocation which depends on that recipe should also not run.

2023-11-12 20:57 UTC, casey commented on .gitignore
> +.vscode/
This should be:

```suggestion
/.vscode
```

Also, the lines in this file should be sorted.

2023-11-12 20:57 UTC, casey commented on src/attribute.rs
> +  Confirm
These enum variants should be sorted.

2023-11-12 20:57 UTC, casey commented on src/recipe.rs
> +  pub(crate) fn confirm(&self) -> bool {
This function should be fallible, since `read_line` can fail, so it should return `RunResult<bool>`

2023-11-12 20:57 UTC, casey commented on src/recipe.rs
>        if comment_line {
Extra whitespace:

```suggestion
      if comment_line {
```

2023-11-12 20:57 UTC, casey commented on src/recipe.rs
> +      std::io::stdin().read_line(&mut buf).is_ok() && buf.trim_end().eq_ignore_ascii_case("y")
```suggestion
      let mut line = String::new();
      std::io::stdin().read_line(&mut line)?;
      let line = line.trim().to_lowercase();
      line == "y" || line == "yes"
```

2023-11-13 11:27 UTC, Hwatwasthat commented
> I just added some comments, and I thought of something else: If a recipe doesn't run, any recipe in the current invocation which depends on that recipe should also not run.

I've added in the confirmation during the running of dependencies. Now, if a recipe that requires confirmation is run as a dependency and is not confirmed then it will return an error of type `DependencyNotConfirmed`, which I could only find a way to insert the name of the dependency being run, I can't find an easy way to inject the parents name without adding in a lot more convolution.

The confirmation is carried out at the start of the `Justfile::run_recipe` function, as I couldn't see another place to put it that would prevent anything running and would allow the returning of an error rather than the ok of a single recipe that is being run (as that would stop any later recipes that were from running as I understand it, which is not the intended use of confirmation (again, as I understand it).

2023-11-13 13:42 UTC, Hwatwasthat commented
Apologies, on testing a bit I realised that I've added in a double confirm. I'll figure out the best way to resolve this and then update the pull.

2023-11-14 01:01 UTC, casey commented
Aside from the double confirm, that all sounds good. I think returning an error if a recipe isn't confirmed is sensible. I think that if we get to a recipe that needs confirmation, and it isn't confirmed, we can abort the whole run, and not run any other recipes. Although it is true that we could run any recipes which aren't dependencies of the unconfirmed recipe, not running them doesn't seem like a big deal.

Also, this will require a couple of tests: One that a recipe that requires and receives confirmation runs, and one that a recipe which requires confirmation but doesn't receive it does not run.

2023-11-14 01:02 UTC, casey commented
Also, if you feel like adding a `--yes` flag that confirms all recipes (per this comment https://github.com/casey/just/issues/1711#issuecomment-1807732753) which seems useful, go for it, otherwise it can be left to another PR.

2023-11-14 09:34 UTC, Hwatwasthat commented
> Aside from the double confirm, that all sounds good. I think returning an error if a recipe isn't confirmed is sensible. I think that if we get to a recipe that needs confirmation, and it isn't confirmed, we can abort the whole run, and not run any other recipes. Although it is true that we could run any recipes which aren't dependencies of the unconfirmed recipe, not running them doesn't seem like a big deal.
> 
> Also, this will require a couple of tests: One that a recipe that requires and receives confirmation runs, and one that a recipe which requires confirmation but doesn't receive it does not run.

Ok, that makes things easier then, I've got a version working that does that so I'll just plow on with it. Tests to come with that in the next commit.

2023-11-14 16:57 UTC, Hwatwasthat commented
> Also, if you feel like adding a `--yes` flag that confirms all recipes (per this comment [#1711 (comment)](https://github.com/casey/just/issues/1711#issuecomment-1807732753)) which seems useful, go for it, otherwise it can be left to another PR.

I was just wondering on the name. yes is a bit ambiguous, maybe `--force-confirm` (just to make it clear), I feel like `--force` or `--no-confirm` doesn't work, as force is ambiguous and no confirm reads to me as the inverse (automatically denying confirm stuff). I have a flag working, right now it's `--yes`.

2023-11-16 23:51 UTC, merged

2023-11-16 23:51 UTC, casey approved these changes
I tweaked a few error messages, as well as printed the error confirmation message to stderr, which is also line-buffered, so no need to flush.

Thanks for the PR!