Add a fallback to wget if curl is not available
casey/just pull request #1913
Opened 2024-02-20 02:24 UTC by tgross35

This allows using the install script on Alpine containers and other busybox-based systems with no additional dependencies.

The script attempts to use `--https-only --secure-protocol=TLSv1_3 --no-verbose` if available, otherwise falls back to a portable wget call.

Additionally, error on invalid arguments (currently syntax errors silently continue).

This is based on top of https://github.com/casey/just/pull/1912, which should be merged first. The main change for this PR is in the second commit.

2024-02-20 05:45 UTC, casey requested changes
Seems reasonable to me! There are conflicts because along with your shellcheck PR, I also added a check on CI which runs shellcheck, but they should to be easy to merge.

2024-02-20 05:45 UTC, casey commented on www/install.sh
> +    # Some wget implementations support these flags, but busybox
How about trying `wget` with all options and then falling back to using none of the options if that fails? We might try the download twice, if there's some other error, like the network not being up, but that might be better than checking each flag individually?

2024-02-20 06:12 UTC, tgross35 commented on www/install.sh
> +    # Some wget implementations support these flags, but busybox
That sounds reasonable, I updated to do this and tested with both ubuntu and alpine. I had to suppress stderr from the first run so it doesn't print the help message on Alpine, but that should be fine.

2024-02-20 06:14 UTC, tgross35 commented on www/install.sh
> +    # Some wget implementations support these flags, but busybox
Actually... maybe we don't want to just try twice? With the change, if HTTPS fails or TLS is outdated then it will just rerun without the flags :)

I don't think the flags actually add much since the URL is https, your call for what to do

2024-05-15 01:00 UTC, casey commented
Is it just old versions of wget which don't support those flags? I think perhaps we should always use those flags, since I'm a little bit wary of not using them just because they aren't supported.

2024-05-21 00:18 UTC, casey approved these changes
I removed the fallback to insecure wget. This fallback would have triggered if there was a cert error, so a MITM could potentially have intentionally downgraded the connection to insecure wget.

If it's necessary to support boxes that don't have a secure curl or wget, we should add a `--insecure` flag download with forcing TLS.

2024-05-21 00:20 UTC, merged