Allow listing of groups (also recursively)
casey/just pull request #2298
Opened 2024-08-02 22:13 UTC by Spatenheinz

This commit is in reference to: https://github.com/casey/just/issues/2195

It took me some time to implement this feature, with getting to understand the layout, trying to parameterize it to remove code duplication and going on vacation. 

With this commit it should be possible to list all occurences of a group. If a submodule and a group has the same name the submodule takes precedence.

It was a nightmare to rebase this. I hope it is working as intended still (at least the tests should pass :D)

Let me know if you like it or not, and if you would like anything changed.

2024-08-04 21:54 UTC, casey requested changes
I don't think it's a good idea to overload `--list NAME` to mean either "list submodule with `NAME`" or "list group with NAME". Submodules and groups may have the same name, so this is ambiguous.

This also looks, I think, more complicated than it needs to be.

My suggestion is to add a `--group` flag which takes the name of a group. If `--group is passed, then the results of list should be filtered to only show recipes which match the given group name. I think the existing list code can be largely unchange, aside from the addition of a few:

```rust
if let Some(group) = &config.group {
  if !recipe.groups().contains(group) {
    continue;
  }
}
```

2024-08-05 07:23 UTC, Spatenheinz commented
I can look into making it less confusing (although most of what i have done is to not repeat too much code between listing of a group and of a submodule), but looking at it again it can probably be done in a better way.

Regarding the `--group`, either I have completely misunderstood you or you shifted your opinion since I opened https://github.com/casey/just/issues/2195 :

https://github.com/casey/just/issues/2195#issuecomment-2192821668

2024-08-05 07:35 UTC, casey commented
Yah I think looking at the implementation, and how much simpler `just --list --group FOO` would be made me change me ind.

2024-08-05 07:35 UTC, casey commented
Sorry to flip flop!

2024-08-05 11:34 UTC, Spatenheinz commented
its all good. I will try and see to it.

2026-04-01 18:19 UTC, casey commented
It is now possible to do `just --list --group foo`.

2026-04-01 18:19 UTC, closed without merging