Dump individual recipes by name
casey/just pull request #2318
Opened 2024-08-25 11:09 UTC by neunenak

This commit modifies the `--dump` option to optionally take the name of a recipe as an argument, and only dump the contents of that single recipe. Resolves https://github.com/casey/just/issues/737

2024-08-25 21:39 UTC, casey requested changes
Nice! A couple thoughts:

- Like `--show` this should probably take a `ModulePath` so submodule recipes can be dumped, and ideally, it should be possible to dump a submodule if the name resolves to a module and not a recipe.
- This should probably reuse the `UnknownRecipe` error.

2024-08-26 08:30 UTC, neunenak commented
> Nice! A couple thoughts:
> 
>     * Like `--show` this should probably take a `ModulePath` so submodule recipes can be dumped, and ideally, it should be possible to dump a submodule if the name resolves to a module and not a recipe.
> 
>     * This should probably reuse the `UnknownRecipe` error.

Hm, is `--dump <recipe>` actually doing anything different than `--show <recipe>`? Should it?

2024-08-26 23:52 UTC, casey commented
Whoops 😅 Yah it looks like show already shows a recipe, and dump shows the entire justfile. Looking at #737, it looks like what's being requested is a way to print the *evaluated* recipe, i.e., including interpolations, so you can see what is going to be executed.

2024-08-27 00:49 UTC, neunenak commented
So maybe it makes sense if `--dump` always printed out the pre-evaluation version of a recipe (or the whole justfile); and `--show` printed out a post-evaluation version. This would involve making `--dump <recipe>` do the same thing that `--show <recipe>` currently does, and then changing the behavior of `--show <recipe>` to something new.

2024-08-27 01:46 UTC, casey commented
I think it's probably not worth breaking changes. I would keep `--show` for recipes and `--dump` for justfiles, and add a flag that changes the behavior of `--show`.

2024-09-16 07:58 UTC, closed without merging