(WIP) Use ariadne
casey/just pull request #2426
Opened 2024-10-10 18:03 UTC by neunenak

https://github.com/casey/just/issues/1323

2024-10-10 18:05 UTC, neunenak commented
I deliberately introduced a compile error, here's what that looks like currently:

```
just -l
error: Attribute `group` got 2 arguments but takes 1 argument
  ——▶ justfile:15:2
   │
15 │ [group('test', 'bogus extra argument')]
   │  ^^^^^
   ```
   
   and here's what that looks like with ariadne as it's currently set up in that PR:
   
   ```
   [01] Error: Attribute argument count mismatch
    ╭─[justfile:15:2]
    │
 15 │ [group('test', 'bogus extra argument')]
    │  ──┬──
    │    ╰──── Found 2 arguments
    │
    │ Note: `group` takes 1 argument
────╯
```

slightly nicer I suppose

2024-10-10 18:21 UTC, casey commented
Is the formatting off in that error message? It looks misaligned.

2024-10-11 07:57 UTC, neunenak commented
> Is the formatting off in that error message? It looks misaligned.

Huh, yeah, must've happened when I copy-pasted it from the terminal, it looks fine there. Screenshot:
![ariadne](https://github.com/user-attachments/assets/fe4d2d16-186f-4d3a-be54-f5fbcf76b46b)

And the current error message in the same terminal:


![current](https://github.com/user-attachments/assets/4597e6a0-4feb-4dae-9023-06e943f814ce)

2024-10-11 09:00 UTC, neunenak commented
Another error:

![duplicate](https://github.com/user-attachments/assets/ab561ff3-5a62-4c16-ab40-14a6262ac92d)

2024-10-12 02:36 UTC, casey commented
Tentatively, I think this looks good. This will be a *massive* change though, because there are so many tests which check error messages.

I think the easiest way to do this would be to land a commit which switches to ariadne, but which doesn't change any error messages or try to add any additional highlights. I think we could write a script to automatically convert existing tests to the new format.

Then we could start improving the error messages one by one, by adding additional spans, etc.

Some questions:

- Can "Error:" be made lowercase?
- Can the error numbers (i.e. `[E01]`) be removed?
- Can the underline be made red, to indicate that it's an error? (For existing errors, the underlined token is always an error, so it should be red, and then if we add additional spans, like hints, those could be a different color)

2024-10-12 08:26 UTC, neunenak commented
> Tentatively, I think this looks good. This will be a _massive_ change though, because there are so many tests which check error messages.
> 
> I think the easiest way to do this would be to land a commit which switches to ariadne, but which doesn't change any error messages or try to add any additional highlights. I think we could write a script to automatically convert existing tests to the new format.
> 
> Then we could start improving the error messages one by one, by adding additional spans, etc.

This makes sense


> Some questions:
> 
>  Can "Error:" be made lowercase?

Yeah. You have to do this in the kinda-silly way of defining `ReportKind::Custom("error", Color::Red)`, and using that in place of `ReportKind::Error` when building the ariadne `Report`, but that works fine. 

>  Can the error numbers (i.e. `[E01]`) be removed?

Yeah, that's totally optional. I kind of like the idea of having a rustc-style authoritative list of error codes, but that's not worth trying to merge in the first pass in any case.

> Can the underline be made red, to indicate that it's an error? (For existing errors, the underlined token is always an error, so it should be red, and then if we add additional spans, like hints, those could be a different color)

Yeah there's an API for assigning pretty arbitrary colors to labels:

![formatting](https://github.com/user-attachments/assets/de2e90c8-9489-4b51-ad41-79ca78e9fd9a)

2024-10-12 17:55 UTC, casey commented
> Yeah. You have to do this in the kinda-silly way of defining `ReportKind::Custom("error", Color::Red)`, and using that in place of `ReportKind::Error` when building the ariadne `Report`, but that works fine.

Dope.

> Yeah, that's totally optional. I kind of like the idea of having a rustc-style authoritative list of error codes, but that's not worth trying to merge in the first pass in any case.

I like the idea of doing that too, although definitely later.

> > Can the underline be made red, to indicate that it's an error? (For existing errors, the underlined token is always an error, so it should be red, and then if we add additional spans, like hints, those could be a different color)
> 
> Yeah there's an API for assigning pretty arbitrary colors to labels:

Dope.

So yeah, I think this is a good change, although the search and replace for changing all the tests will be brutal.

2024-11-27 22:22 UTC, casey commented
An idea that might make this easier: Can we style the adriane errors so that they look the same as `just` errors, which would let us merge this with minimal changes to the tests? We could follow up with PRs which improved the style using adriane features, which would require changing the tests, but hopefully could be entirely automated. This PR is likely to keep accumulating conflicts which might make it hard to land.

2024-12-03 03:32 UTC, neunenak commented
> An idea that might make this easier: Can we style the adriane errors so that they look the same as `just` errors, which would let us merge this with minimal changes to the tests? We could follow up with PRs which improved the style using adriane features, which would require changing the tests, but hopefully could be entirely automated. This PR is likely to keep accumulating conflicts which might make it hard to land.

I'm not sure there's an easy way to make the error output look like just errors. I was having some trouble with tests not matching, which I realized was because ariadne was always emitting ansi color codes even in tests; so I added some functionality to pass color enable/disable to ariadne which solves that problem.  Now it's just a matter of updating the tests, which I was trying to find a way to use an AI code editor to do. If not I'll write a script for it or do it manually.

2026-02-25 01:18 UTC, neunenak commented
@casey in the year or so since I last looked at this, LLMs got good enough to make the code changes in a (relatively) non-tedious way, so this PR is ready for review.

2026-03-29 22:25 UTC, casey requested changes
I just checked this out, and source locations are missing underlining:

<img width="1188" height="454" alt="Screenshot 2026-03-29 at 3 22 23 PM" src="https://github.com/user-attachments/assets/1a7b3784-7afe-447c-b2c3-531c530ad5b6" />

There should be an indication of where the error occurred, and it shouldn't just be a color change, in case colors are disabled.

Also, `Error` is now uppercase, when it should be lowercsae.

Also, for the initial PR, I think we should remove special rendering for specific error messages. It's nice, but they make the PR harder to review, and I'd rather follow up with individual improvements to specific error messages.

2026-07-11 23:43 UTC, casey commented
Closing, since this is pretty stale.

2026-07-11 23:43 UTC, closed without merging