Print recipe signature if missing arguments
casey/just pull request #369
Opened 2018-10-28 23:29 UTC by ladysamantha

references issue #341 

Wasn't sure what format would be the best, but I took a stab at it and and printed out a simple usage doc on top of the error that was already there. Let me know what more I can do to help/make the code cleaner! I'm still fairly new to rust, so if this seems like a naÏve approach, please forgive me :laughing:

2018-10-29 05:47 UTC, casey commented
Thank you for the PR! I think this a stray commit. You might want to create a separate branch for the pull request, so that pushes to master don't land on the PR after you've opened it.

2018-10-29 05:55 UTC, casey requested changes
Parameters have a `Display` implementation, so that should be reused to format optional and 
 variadic parameters, and to color the usage string. I use the `{:#}` formatter for colored output. Since this message is being printed to stderr, it should use `{:#}` of stderr is attached to a terminal, and `{}` otherwise. Check out `run.rs` for how to do this.

2018-10-29 05:55 UTC, casey commented on src/runtime_error.rs
> +          write!(f, "Usage:\n just {} {}", recipe, parameters.join(" "));
Nit: Usage should be lowercase, since `error:` is also lowercase.

2018-10-29 06:00 UTC, casey commented on src/runtime_error.rs
> +          write!(f, "Usage:\n just {} {}", recipe, parameters.join(" "));
Also, let's go with four spaces of indentation in front of the word `just`.

2018-10-29 19:37 UTC, casey requested changes

2018-10-29 19:37 UTC, casey commented on src/justfile.rs
> -        assert_eq!(parameters, ["b", "c", "d"]);
For the tests, let's leave in the assertion that the names are right. You can collect into a vec of the recipe names and compare with that.

2018-10-30 01:45 UTC, ladysamantha commented
> Thank you for the PR! I think this has a stray 2nd commit. You might want to create a separate branch for the pull request, so that pushes to master don't land on the PR after you've opened it.

D'oh! That actually makes sense, I'm just so used to not using branches at work (company policy...) so I forget sometimes to use them lol

Did you want the usage printed on all of the conditions in `ArugmentCountMismatch`?

2018-10-31 06:06 UTC, casey requested changes
Sweet, thanks for making those changes. We should check stderr instead of stdout, and I think we should print the usage string in all cases. After that this should be good to go.

2018-11-03 21:51 UTC, merged

2018-11-03 21:51 UTC, casey commented
Awesome, thank for your contribution!

2018-11-03 23:49 UTC, ladysamantha commented
Thank you! Happy to contribute :blue_heart: