Add docs for justfile and justfile_directory functions
casey/just pull request #726
Opened 2020-11-19 20:49 UTC by rminderhoud

Added some basic documentations for the `justfile()` and `justfile_directory()` that were previously undocumented. These functions were added in https://github.com/casey/just/pull/569 but the only information about them was in the source code and this issue https://github.com/casey/just/issues/387

2020-11-19 22:53 UTC, casey requested changes
Thank you very much for spotting this! Looks good, aside from a couple small points around wording and punctuation.

CI initially failed, so I fixed those errors in #727 and merged them into this branch, so you might have to pull before pushing.

2020-11-19 22:53 UTC, casey commented on README.adoc
> +- `justfile()` - Retrieves the path to the current justfile
How about "Retrieves the path of the current justfile."?

2020-11-19 22:53 UTC, casey commented on README.adoc
> +- `justfile_directory()` - Retrieves the path to the parent directory of the current justfile
"Retrieves the path of the parent directory of the current justfile."

2020-11-19 22:53 UTC, casey commented on README.adoc
> +For example, if you need to run a command relative to the current justfile, you could do the following:
How about: "For example, to run a command relative to the location of the current justfile:"

2020-11-19 23:01 UTC, rminderhoud commented
Sounds good, I updated the wording to match your recommendations and rebased your CI changes. Hopefully it doesn't fail now :)

2020-11-20 01:20 UTC, merged

2020-11-20 01:20 UTC, casey commented
Awesome, merged. Thank you very much!